$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$baseDir = $PSScriptRoot
$dbPath = Join-Path $baseDir "notes.txt"

# Create file if missing entirely
if (-not (Test-Path -LiteralPath $dbPath)) {
    $initText = "Info: Auto-generated by PB`r`n--------------------------------------------------------------------`r`n"
    Set-Content -LiteralPath $dbPath -Value $initText -Encoding UTF8
}

function Process-Command {
    param([string]$InputStr)
    
    $action = ""
    $value = ""
    $isSearch = $false
    
    $InputStr = $InputStr.Trim()
    
    # Parse user input securely
    if ($InputStr -eq "n" -or $InputStr -eq "e" -or $InputStr -eq "-init") {
        $action = $InputStr
    } elseif ($InputStr.StartsWith("-add ")) {
        $action = "-add"
        $value = $InputStr.Substring(4).Trim().Trim('"') 
    } elseif ($InputStr.StartsWith("-del ")) {
        $action = "-del"
        $value = $InputStr.Substring(4).Trim().Trim('"')
    } elseif ($InputStr -eq "q" -or $InputStr -eq "exit" -or $InputStr -eq "quit") {
        exit
    } elseif ($InputStr -ne "") {
        $isSearch = $true
        $searchQueryRaw = $InputStr
    }

    # Action: Edit / Explore
    if ($action -eq "n") { Start-Process notepad.exe $dbPath; return }
    if ($action -eq "e") { Invoke-Item $baseDir; return }
    
    # Action: Initialize Template
    if ($action -eq "-init") {
        if (Test-Path -LiteralPath $dbPath) { 
            Write-Host "`n [!] notes.txt already exists. Delete or rename it to generate the demo.`n" -ForegroundColor Red
            return 
        }
        $initLines = @(
            '"Info: Auto-generated by PB"',
            '"--------------------------------------------------------------------"',
            '"// INSTRUCTIONS & ADVANCED OPTIONS"',
            '"// - Format: Name  Phone  #Group  !Color"',
            '"// - Note: Leave at least TWO spaces between Name and Phone!"',
            '"// - Groups: Add #Name (e.g., #Work) to create a category folder."',
            '"// - Colors: Add !Color (e.g., !Red, !Cyan, !Yellow, !Magenta)."',
            '"// - Comments: Any line starting with // is hidden from UI."',
            '"--------------------------------------------------------------------"',
            '"John Doe        555-0100   #VIP !Green"',
            '"Jane Smith      555-0200   #Work !Cyan"',
            '"Local Pizza     555-9999   #Food"'
        )
        Set-Content -LiteralPath $dbPath -Value $initLines -Encoding UTF8
        Write-Host "`n ✔ Template notes.txt generated. Press ENTER to refresh." -ForegroundColor Green
        return
    }

    # Action: Add / Delete Data
    if ($action -eq "-add") {
        if ([string]::IsNullOrWhiteSpace($value)) { Write-Host "`n [!] Invalid. Example: -add `"Name 123`"" -ForegroundColor Red; return }
        Copy-Item -LiteralPath $dbPath -Destination "$dbPath.bak" -Force
        Add-Content -LiteralPath $dbPath "`"$value`"" -Encoding UTF8
        $action = "" 
    }

    if ($action -eq "-del") {
        if ([string]::IsNullOrWhiteSpace($value)) { Write-Host "`n [!] Invalid. Example: -del `"Name`"" -ForegroundColor Red; return }
        Copy-Item -LiteralPath $dbPath -Destination "$dbPath.bak" -Force
        $lines = @(Get-Content -LiteralPath $dbPath -Encoding UTF8)
        $keep = @($lines | Where-Object { $_ -notmatch [regex]::Escape($value) -or $_ -match "^Info:" -or $_ -match "^---" -or $_ -match "^//" })
        Set-Content -LiteralPath $dbPath -Value $keep -Encoding UTF8
        $action = "" 
    }

    # --- Parse notes.txt ---
    $lines = @(Get-Content -LiteralPath $dbPath -Encoding UTF8)
    $results = @()

    foreach ($line in $lines) {
        $clean = $line.Trim().Trim('"')
        
        # Ignore old batch commands and new // comments
        if ([string]::IsNullOrWhiteSpace($clean) -or $clean -match "^---" -or $clean -match "^Info:" -or $clean -match "/HELP" -or $clean -match "=" -or $clean -match "^//") { continue }
        
        $group = "General"
        $color = ""

        if ($clean -match "#([a-zA-Z0-9_]+)") {
            $group = $matches[1]
            $clean = $clean -replace "#$group", ""
        }
        if ($clean -match "!(Red|Yellow|Green|Cyan|Blue|Magenta|White|Gray|DarkGray|DarkCyan)") {
            $color = $matches[1]
            $clean = $clean -replace "!$color", ""
        }

        $clean = $clean.Trim()
        $parts = $clean -split "\s{2,}"
        
        if ($parts.Count -ge 2) {
            $results += [PSCustomObject]@{ Name = $parts[0]; Phone = $parts[1]; Group = $group; Color = $color }
        } else {
            $results += [PSCustomObject]@{ Name = $clean; Phone = ""; Group = $group; Color = $color }
        }
    }

    # --- Search Filter ---
    if ($isSearch) {
        $searchQueryEsc = [regex]::Escape($searchQueryRaw)
        $results = @($results | Where-Object { 
            ($null -ne $_.Name -and $_.Name -match $searchQueryEsc) -or 
            ($null -ne $_.Phone -and $_.Phone -match $searchQueryEsc) -or 
            ($null -ne $_.Group -and $_.Group -match $searchQueryEsc) 
        })
    }

    # --- UI Rendering (Nala-Style) ---
    Clear-Host
    
    # Custom Title Block
    Write-Host "`n  ─────────────────────────────────────────────────────────────────" -ForegroundColor DarkCyan
    Write-Host "  📦 PHONEBOOK v.2.1" -ForegroundColor Cyan
    Write-Host "  Created by Nikos Georgousis " -ForegroundColor White -NoNewline
    Write-Host "| " -ForegroundColor DarkGray -NoNewline
    Write-Host "Original idea by Scott Brodsky" -ForegroundColor Gray
    Write-Host "  ─────────────────────────────────────────────────────────────────" -ForegroundColor DarkCyan
    Write-Host "  📍 $baseDir`n" -ForegroundColor DarkGray

    if ($isSearch) { Write-Host "  🔍 Search: '$searchQueryRaw'`n" -ForegroundColor Yellow }

    if ($results.Count -gt 0) {
        $maxLen = 30
        foreach ($r in $results) { if ($r.Name.Length -gt $maxLen) { $maxLen = $r.Name.Length } }
        $maxLen += 5 

        $groupedResults = $results | Sort-Object Group, Name | Group-Object Group

        foreach ($g in $groupedResults) {
            Write-Host "  📂 $($g.Name.ToUpper())" -ForegroundColor DarkCyan
            Write-Host "  $('-' * ($maxLen + 15))" -ForegroundColor DarkGray
            
            $i = 0
            foreach ($item in $g.Group) {
                $rowColor = if ($item.Color) { $item.Color } elseif ($i % 2 -eq 0) { "White" } else { "Gray" }
                Write-Host "  " -NoNewline
                Write-Host $item.Name.PadRight($maxLen) -ForegroundColor $rowColor -NoNewline
                Write-Host $item.Phone -ForegroundColor Green
                $i++
            }
            Write-Host "" # Spacing between groups
        }
    } else {
        Write-Host "  ❌ No matches found.`n" -ForegroundColor Red
    }

    # --- The Full, Readable Help Menu ---
    Write-Host "  ─────────────────────────────────────────────────────────────────" -ForegroundColor DarkGray
    
    $safeCount = if ($null -ne $results) { @($results).Count } else { 0 }
    Write-Host "  Total records: $safeCount`n" -ForegroundColor Cyan
    
    Write-Host "  💡 HOW TO USE THE PHONEBOOK:" -ForegroundColor Yellow
    Write-Host "  Search for a contact : " -ForegroundColor DarkGray -NoNewline; Write-Host "Type <name, number, or #group>" -ForegroundColor White
    Write-Host "  Add a new contact    : " -ForegroundColor DarkGray -NoNewline; Write-Host "-add `"Name Number #Group !Color`"" -ForegroundColor Green
    Write-Host "  Delete a contact     : " -ForegroundColor DarkGray -NoNewline; Write-Host "-del `"Name`"" -ForegroundColor Red
    Write-Host "  Generate Template    : " -ForegroundColor DarkGray -NoNewline; Write-Host "-init" -ForegroundColor Magenta
    Write-Host "  Edit in Notepad      : " -ForegroundColor DarkGray -NoNewline; Write-Host "n" -ForegroundColor Cyan
    Write-Host "  Open Folder          : " -ForegroundColor DarkGray -NoNewline; Write-Host "e" -ForegroundColor Cyan
    Write-Host "  Quit Application     : " -ForegroundColor DarkGray -NoNewline; Write-Host "q`n" -ForegroundColor Yellow
}

# --- Launch Mode Selection ---
if ($args.Count -gt 0) {
    $cliArgs = $args -join " "
    Process-Command $cliArgs
    exit
}

Process-Command "" 

while ($true) {
    $prompt = Read-Host "  pb> "
    Process-Command $prompt
}