$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$baseDir = $PSScriptRoot
$dbPath = Join-Path $baseDir "notes.txt"

if (-not (Test-Path -LiteralPath $dbPath)) {
    $initText = "Info: Auto-generated by PB`r`n--------------------------------------------------------------------`r`n"
    try { Set-Content -LiteralPath $dbPath -Value $initText -Encoding UTF8 } catch {}
}

Add-Type -AssemblyName System.Windows.Forms, System.Drawing

function Set-WindowToMouseScreen {
    Start-Sleep -Milliseconds 150
    
    $signature = @'
    [DllImport("user32.dll")]
    public static extern bool SetProcessDPIAware();
    [DllImport("user32.dll")]
    public static extern bool GetWindowRect(IntPtr hWnd, out RECT lpRect);
    [DllImport("user32.dll")]
    public static extern bool MoveWindow(IntPtr hWnd, int X, int Y, int nWidth, int nHeight, bool bRepaint);
    [DllImport("kernel32.dll")]
    public static extern IntPtr GetConsoleWindow();
    [DllImport("user32.dll")]
    public static extern IntPtr GetAncestor(IntPtr hWnd, uint gaFlags);
    public struct RECT { public int Left; public int Top; public int Right; public int Bottom; }
'@
    if (-not ("Win32.Win32Utils" -as [type])) {
        Add-Type -MemberDefinition $signature -Name "Win32Utils" -Namespace "Win32" -PassThru | Out-Null
    }
    
    [Win32.Win32Utils]::SetProcessDPIAware() | Out-Null
    
    $hwnd = [Win32.Win32Utils]::GetConsoleWindow()
    $topHwnd = [Win32.Win32Utils]::GetAncestor($hwnd, 2)
    if ($topHwnd -eq [IntPtr]::Zero) { $topHwnd = $hwnd }
    
    if ($topHwnd -ne [IntPtr]::Zero) {
        $mousePos = [System.Windows.Forms.Cursor]::Position
        $currentScreen = [System.Windows.Forms.Screen]::FromPoint($mousePos)
        $screenArea = $currentScreen.WorkingArea
        
        $rect = New-Object Win32.Win32Utils+RECT
        [Win32.Win32Utils]::GetWindowRect($topHwnd, [ref]$rect) | Out-Null
        $wWidth = $rect.Right - $rect.Left
        $wHeight = $rect.Bottom - $rect.Top
        
        if ($wWidth -eq 0 -or $wHeight -eq 0) { $wWidth = 800; $wHeight = 600 }
        
        $posX = $screenArea.Left + [math]::Max(0, [math]::Round(($screenArea.Width - $wWidth) / 2))
        $posY = $screenArea.Top + [math]::Max(0, [math]::Round(($screenArea.Height - $wHeight) / 2))
        
        [Win32.Win32Utils]::MoveWindow($topHwnd, $posX, $posY, $wWidth, $wHeight, $true) | Out-Null
    }
}

Set-WindowToMouseScreen

function Process-Command {
    param([string]$InputStr)
    
    $action = ""
    $value = ""
    $isSearch = $false
    $InputStr = $InputStr.Trim()
    
    if ($InputStr -eq "n" -or $InputStr -eq "e" -or $InputStr -eq "-init" -or $InputStr -eq "-backup") {
        $action = $InputStr
    } elseif ($InputStr.StartsWith("-add ")) {
        $action = "-add"
        $value = $InputStr.Substring(4).Trim().Trim('"') 
    } elseif ($InputStr.StartsWith("-del ")) {
        $action = "-del"
        $value = $InputStr.Substring(4).Trim().Trim('"')
    } elseif ($InputStr.StartsWith("-h ") -or $InputStr.StartsWith("-help ")) {
        $action = "-help"
        if ($InputStr.StartsWith("-h ")) { $value = $InputStr.Substring(3).Trim() } else { $value = $InputStr.Substring(6).Trim() }
    } elseif ($InputStr -eq "-h" -or $InputStr -eq "-help") {
        $action = "-help"
        $value = ""
    } elseif ($InputStr -eq "q" -or $InputStr -eq "exit" -or $InputStr -eq "quit") {
        exit
 } elseif ($InputStr -eq "*") {
        $isSearch = $false
    } elseif ($InputStr -ne "") {
        $isSearch = $true
        $searchQueryRaw = $InputStr
    }

    if ($action -eq "n") { Start-Process notepad.exe $dbPath; return }
    if ($action -eq "e") { Invoke-Item $baseDir; return }
    
    # --- IN-APP HELP SYSTEM ---
    if ($action -eq "-help") {
        Clear-Host
        Set-WindowToMouseScreen
        $boxWidth = 72
        $topicName = if ($value) { $value.ToUpper() } else { "INDEX" }
        
        Write-Host ""
        Write-Host ("  ╭" + ("─" * ($boxWidth - 2)) + "╮") -ForegroundColor DarkCyan
        Write-Host "  │" -ForegroundColor DarkCyan -NoNewline
        Write-Host (" 📘 HELP: " + $topicName).PadRight($boxWidth - 2) -ForegroundColor Cyan -NoNewline
        Write-Host "│" -ForegroundColor DarkCyan
        Write-Host ("  ╰" + ("─" * ($boxWidth - 2)) + "╯") -ForegroundColor DarkCyan
        Write-Host ""

        switch ($value.ToLower()) {
            "color" {
                Write-Host "  Use colors to visually highlight specific contacts in your list." -ForegroundColor White
                Write-Host "  Syntax: Append '!ColorName' anywhere on the contact's line.`n" -ForegroundColor DarkGray
                Write-Host "  Supported Colors:" -ForegroundColor Yellow
                Write-Host "  Black, DarkBlue, DarkGreen, DarkCyan, DarkRed, DarkMagenta," -ForegroundColor White
                Write-Host "  DarkYellow, Gray, DarkGray, Blue, Green, Cyan, Red, Magenta," -ForegroundColor White
                Write-Host "  Yellow, White`n" -ForegroundColor White
                Write-Host "  Example:" -ForegroundColor Gray
                Write-Host "  -add `"John Doe 555-0100 !Red`"" -ForegroundColor Green
            }
            "groups" {
                Write-Host "  Groups allow you to organize contacts into distinct category blocks." -ForegroundColor White
                Write-Host "  Syntax: Append '#GroupName' anywhere on the contact's line.`n" -ForegroundColor DarkGray
                Write-Host "  How it works:" -ForegroundColor Yellow
                Write-Host "  - The script automatically intercepts the tag, groups identical" -ForegroundColor White
                Write-Host "    tags together, and alphabetizes them." -ForegroundColor White
                Write-Host "  - Contacts without a hashtag default to the 'GENERAL' group.`n" -ForegroundColor White
                Write-Host "  Example:" -ForegroundColor Gray
                Write-Host "  -add `"Jane Smith 555-0200 #Work`"" -ForegroundColor Green
            }
            "backup" {
                Write-Host "  Creates an instant, safe snapshot of your current database." -ForegroundColor White
                Write-Host "  Syntax: Type '-backup' at the main prompt.`n" -ForegroundColor DarkGray
                Write-Host "  How it works:" -ForegroundColor Yellow
                Write-Host "  - It copies notes.txt and stamps it with the exact date and time" -ForegroundColor White
                Write-Host "    (e.g., notes.txt.20260330_093005.bak)." -ForegroundColor White
                Write-Host "  - Safe Delete: The script ALSO creates a temporary 'notes.txt.bak'" -ForegroundColor DarkGray
                Write-Host "    automatically every time you run the '-add' or '-del' command.`n" -ForegroundColor DarkGray
            }
            "examples" {
                Write-Host "  Adding a new VIP contact:" -ForegroundColor Yellow
                Write-Host "  -add `"John Boss 555-0000 #VIP !Red`"`n" -ForegroundColor Green
                Write-Host "  Searching for a contact:" -ForegroundColor Yellow
                Write-Host "  Just type any part of their name, number, or group:" -ForegroundColor White
                Write-Host "  boss`n" -ForegroundColor Green
                Write-Host "  Deleting a contact:" -ForegroundColor Yellow
                Write-Host "  -del `"John Boss`"`n" -ForegroundColor Red
            }
            "files" {
                Write-Host "  The ecosystem operates entirely on three local files:`n" -ForegroundColor White
                Write-Host "  pb.bat    " -ForegroundColor Cyan -NoNewline; Write-Host "- The Launcher" -ForegroundColor Yellow
                Write-Host "              A tiny batch file that safely bypasses Windows policies" -ForegroundColor DarkGray
                Write-Host "              and routes your commands to the engine.`n" -ForegroundColor DarkGray
                Write-Host "  pb.ps1    " -ForegroundColor Cyan -NoNewline; Write-Host "- The Engine" -ForegroundColor Yellow
                Write-Host "              The core PowerShell script handling the UI and logic.`n" -ForegroundColor DarkGray
                Write-Host "  notes.txt " -ForegroundColor Cyan -NoNewline; Write-Host "- The Database" -ForegroundColor Yellow
                Write-Host "              Your raw data file. MUST be saved as UTF-8 with BOM" -ForegroundColor DarkGray
                Write-Host "              to protect Greek characters.`n" -ForegroundColor DarkGray
            }
            default {
                Write-Host "  Missing or unknown topic. To read the manual, type '-h' followed" -ForegroundColor Red
                Write-Host "  by one of the available topics below:`n" -ForegroundColor Red
                Write-Host "  Available Topics:" -ForegroundColor Yellow
                Write-Host "  -h color    " -ForegroundColor Cyan -NoNewline; Write-Host "(Explains UI color highlighting)" -ForegroundColor White
                Write-Host "  -h groups   " -ForegroundColor Cyan -NoNewline; Write-Host "(Explains category folders)" -ForegroundColor White
                Write-Host "  -h backup   " -ForegroundColor Cyan -NoNewline; Write-Host "(Explains data safety features)" -ForegroundColor White
                Write-Host "  -h examples " -ForegroundColor Cyan -NoNewline; Write-Host "(Shows basic usage commands)" -ForegroundColor White
                Write-Host "  -h files    " -ForegroundColor Cyan -NoNewline; Write-Host "(Explains the ecosystem structure)`n" -ForegroundColor White
            }
        }
        return
    }

    if ($action -eq "-init") {
        if (Test-Path -LiteralPath $dbPath) { Write-Host "`n [!] notes.txt already exists.`n" -ForegroundColor Red; return }
        $initLines = @(
            '"Info: Auto-generated by PB"',
            '"--------------------------------------------------------------------"',
            '"// INSTRUCTIONS & ADVANCED OPTIONS"',
            '"// - Format: Name  Phone  #Group  !Color"',
            '"// - Note: Leave at least TWO spaces between Name and Phone!"',
            '"// - Groups: Add #Name (e.g., #Work) to create a category folder."',
            '"// - Valid Colors: !Red, !Cyan, !Yellow, !Magenta, !Green, !Blue, !DarkGray, !White"',
            '"// - Comments: Any line starting with // is hidden from UI."',
            '"--------------------------------------------------------------------"',
            '"John Doe        555-0100   #VIP !Green"',
            '"Jane Smith      555-0200   #Work !Cyan"',
            '"Local Pizza     555-9999   #Food"'
        )
        try {
            Set-Content -LiteralPath $dbPath -Value $initLines -Encoding UTF8
            Write-Host "`n ✔ Template generated. Press ENTER to refresh." -ForegroundColor Green
        } catch {}
        return
    }

    if (-not (Test-Path -LiteralPath $dbPath)) { Write-Host "`n  ❌ DB missing! Type '-init'`n" -ForegroundColor Red; return }

    if ($action -eq "-backup") {
        try {
            $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
            Copy-Item -LiteralPath $dbPath -Destination "$dbPath.$timestamp.bak" -Force
            Write-Host "`n ✔ Backup created: notes.txt.$timestamp.bak`n" -ForegroundColor Green
        } catch {}
        return
    }

    try {
        if ($action -eq "-add") {
            if ([string]::IsNullOrWhiteSpace($value)) { Write-Host "`n [!] Invalid add format.`n" -ForegroundColor Red; return }
            Copy-Item -LiteralPath $dbPath -Destination "$dbPath.bak" -Force -ErrorAction SilentlyContinue
            Add-Content -LiteralPath $dbPath "`"$value`"" -Encoding UTF8
            $action = "" 
        }
        if ($action -eq "-del") {
            if ([string]::IsNullOrWhiteSpace($value)) { Write-Host "`n [!] Invalid del format.`n" -ForegroundColor Red; return }
            Copy-Item -LiteralPath $dbPath -Destination "$dbPath.bak" -Force -ErrorAction SilentlyContinue
            $lines = @(Get-Content -LiteralPath $dbPath -Encoding UTF8)
            $keep = @($lines | Where-Object { $_ -notmatch [regex]::Escape($value) -or $_ -match "^Info:" -or $_ -match "^---" -or $_ -match "^//" })
            Set-Content -LiteralPath $dbPath -Value $keep -Encoding UTF8
            $action = "" 
        }
    } catch { Write-Host "`n  [!] File Error: locked.`n" -ForegroundColor Red; return }

    try { $lines = @(Get-Content -LiteralPath $dbPath -Encoding UTF8) } catch { return }
    
    $results = @()
    $validColors = "Black|DarkBlue|DarkGreen|DarkCyan|DarkRed|DarkMagenta|DarkYellow|Gray|DarkGray|Blue|Green|Cyan|Red|Magenta|Yellow|White"

    foreach ($line in $lines) {
        $clean = $line.Trim().Trim('"')
        if ([string]::IsNullOrWhiteSpace($clean) -or $clean -match "^---" -or $clean -match "^Info:" -or $clean -match "/HELP" -or $clean -match "=" -or $clean -match "^//") { continue }
        
        $group = "General"
        $color = ""

        if ($clean -match "#([a-zA-Z0-9_]+)") {
            $group = $matches[1]
            $clean = $clean -replace "#$group", ""
        }
        if ($clean -match "!($validColors)") {
            $color = $matches[1]
            $clean = $clean -replace "!$color", ""
        }

        $clean = $clean.Trim()
        $parts = $clean -split "\s{2,}"
        
        if ($parts.Count -ge 2) {
            $results += [PSCustomObject]@{ Name = $parts[0]; Phone = $parts[1]; Group = $group; Color = $color }
        } else {
            $results += [PSCustomObject]@{ Name = $clean; Phone = ""; Group = $group; Color = $color }
        }
    }

    if ($isSearch) {
        $searchQueryEsc = [regex]::Escape($searchQueryRaw)
        $results = @($results | Where-Object { 
            ($null -ne $_.Name -and $_.Name -match $searchQueryEsc) -or 
            ($null -ne $_.Phone -and $_.Phone -match $searchQueryEsc) -or 
            ($null -ne $_.Group -and $_.Group -match $searchQueryEsc) 
        })
    }

    # --- NALA STYLE DYNAMIC WIDTH CALCULATION ---
    $maxNameLen = 20
    $maxPhoneLen = 15
    if ($results.Count -gt 0) {
        foreach ($r in $results) { 
            if ($r.Name.Length -gt $maxNameLen) { $maxNameLen = $r.Name.Length } 
            if ($r.Phone.Length -gt $maxPhoneLen) { $maxPhoneLen = $r.Phone.Length }
        }
    }
    
    $boxWidth = [math]::Max($maxNameLen + $maxPhoneLen + 10, 72)
    $phonePadLen = $boxWidth - 4 - $maxNameLen

    # --- UI RENDERING: TOP TITLE BOX ---
    Clear-Host
    Set-WindowToMouseScreen
    Write-Host ""
    Write-Host ("  ╭" + ("─" * ($boxWidth - 2)) + "╮") -ForegroundColor DarkCyan
    
    Write-Host "  │" -ForegroundColor DarkCyan -NoNewline
    Write-Host (" 📦 PHONEBOOK v.2.3").PadRight($boxWidth - 2) -ForegroundColor Cyan -NoNewline
    Write-Host "│" -ForegroundColor DarkCyan

    $cred1 = " 👤 Created by Nikos Georgousis "
    $cred2 = "| "
    $cred3 = "Original idea by Scott Brodsky"
    $totalCredLen = $cred1.Length + $cred2.Length + $cred3.Length
    $padSpace = $boxWidth - 2 - $totalCredLen
    if ($padSpace -lt 0) { $padSpace = 0 }

    Write-Host "  │" -ForegroundColor DarkCyan -NoNewline
    Write-Host $cred1 -ForegroundColor White -NoNewline
    Write-Host $cred2 -ForegroundColor DarkGray -NoNewline
    Write-Host $cred3 -ForegroundColor Gray -NoNewline
    Write-Host (" " * $padSpace) -NoNewline
    Write-Host "│" -ForegroundColor DarkCyan
    
    Write-Host "  │" -ForegroundColor DarkCyan -NoNewline
    Write-Host (" 📍 $baseDir").PadRight($boxWidth - 2) -ForegroundColor DarkGray -NoNewline
    Write-Host "│" -ForegroundColor DarkCyan
    
    Write-Host ("  ╰" + ("─" * ($boxWidth - 2)) + "╯") -ForegroundColor DarkCyan

    if ($isSearch) { Write-Host "`n  🔍 Search: '$searchQueryRaw'" -ForegroundColor Yellow } else { Write-Host "" }

    # --- MINIMAL MODE CHECK ---
    $showList = $true
    if ($script:minimalMode -and [string]::IsNullOrWhiteSpace($InputStr)) {
        $showList = $false
    }

    if ($showList) {
        if ($results.Count -gt 0) {
            $groupedResults = $results | Sort-Object Group, Name | Group-Object Group

            foreach ($g in $groupedResults) {
                $gName = " " + $g.Name.ToUpper() + " "
                $remLen = $boxWidth - 3 - $gName.Length
                if ($remLen -lt 0) { $remLen = 0 }
                
                Write-Host ("  ╭─") -ForegroundColor DarkCyan -NoNewline
                Write-Host $gName -ForegroundColor DarkCyan -BackgroundColor Black -NoNewline
                Write-Host ("─" * $remLen + "╮") -ForegroundColor DarkCyan
                
                $i = 0
                foreach ($item in $g.Group) {
                    $rowColor = "White"
                    if ($item.Color -and [Enum]::IsDefined([ConsoleColor], $item.Color)) {
                        $rowColor = $item.Color
                    } elseif ($i % 2 -eq 0) { $rowColor = "White" } else { $rowColor = "Gray" }
                    
                    Write-Host "  │ " -ForegroundColor DarkCyan -NoNewline
                    Write-Host ($item.Name.PadRight($maxNameLen)) -ForegroundColor $rowColor -NoNewline
                    Write-Host " " -NoNewline
                    Write-Host ($item.Phone.PadRight($phonePadLen)) -ForegroundColor Green -NoNewline
                    Write-Host "│" -ForegroundColor DarkCyan
                    $i++
                }
                Write-Host ("  ╰" + ("─" * ($boxWidth - 2)) + "╯") -ForegroundColor DarkCyan
            }
        } else {
            $errBoxWidth = 30
            Write-Host ""
            Write-Host ("  ╭" + ("─" * ($errBoxWidth - 2)) + "╮") -ForegroundColor Red
            Write-Host "  │" -ForegroundColor Red -NoNewline
            Write-Host (" ❌ No matches found.").PadRight($errBoxWidth - 3) -ForegroundColor Red -NoNewline
            Write-Host "│" -ForegroundColor Red
            Write-Host ("  ╰" + ("─" * ($errBoxWidth - 2)) + "╯") -ForegroundColor Red
        }
    }

    $safeCount = if ($null -ne $results) { @($results).Count } else { 0 }
    if ($showList) {
        Write-Host "`n  Total records: $safeCount" -ForegroundColor Cyan
    } else {
        Write-Host "`n  Total records: $safeCount (Search * to display the entire list)" -ForegroundColor DarkGray
    }
    
    Write-Host ""
    Write-Host "  💡 DASHBOARD:" -ForegroundColor Yellow
    
    Write-Host "  Search : " -ForegroundColor DarkGray -NoNewline; Write-Host "Type keyword (or * for all)".PadRight(28) -ForegroundColor White -NoNewline
    Write-Host "Add    : " -ForegroundColor DarkGray -NoNewline; Write-Host "-add `"Name Num #Grp !Col`"" -ForegroundColor Green

    Write-Host "  Delete : " -ForegroundColor DarkGray -NoNewline; Write-Host "-del `"Name`"".PadRight(28) -ForegroundColor Red -NoNewline
    Write-Host "Backup : " -ForegroundColor DarkGray -NoNewline; Write-Host "-backup" -ForegroundColor DarkCyan

    Write-Host "  Edit   : " -ForegroundColor DarkGray -NoNewline; Write-Host "n".PadRight(28) -ForegroundColor Cyan -NoNewline
    Write-Host "Folder : " -ForegroundColor DarkGray -NoNewline; Write-Host "e" -ForegroundColor Cyan

    Write-Host "  Init   : " -ForegroundColor DarkGray -NoNewline; Write-Host "-init".PadRight(28) -ForegroundColor Magenta -NoNewline
    Write-Host "Help   : " -ForegroundColor DarkGray -NoNewline; Write-Host "-h <topic>" -ForegroundColor Cyan

    Write-Host "`n  Quit   : " -ForegroundColor DarkGray -NoNewline; Write-Host "q`n" -ForegroundColor Yellow
}

# --- CLI ARGUMENT PARSER ---
$script:minimalMode = $false
$execArgs = @()

foreach ($arg in $args) {
    if ($arg -eq "-m") { $script:minimalMode = $true }
    else { $execArgs += $arg }
}

if ($execArgs.Count -gt 0) {
    Process-Command ($execArgs -join " ")
    exit
}

Process-Command "" 

while ($true) {
    $prompt = Read-Host "  pb> "
    Process-Command $prompt
}